apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: support-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgAG6hKFD1DNx9WGJD8fvz9nB9/c88oEgVZoN4T3kkq/nl6z4Z9zkuc154GeNSpHAKdCP5GvgURphNNZDy97TGjO0JD3R3d35FU2UDJXf2Yl+EHBEIav80vMF792CjPSPlkx/6I6DWY9/e39j730D0H4cZeUcS2JlWZZ8JZM2CoIOuiX9xDG4rQ+05mEFviYr2M/SjC9kf4EaECPCpK7BEr+MNhilycsT0DrGxQViudhg1YmylQHNGzJ0BjFx8ExrRa7tIfahB1/wnTuposNnS9XG/FiUHjLYOCZUu4uQNIkfIQm8xBcQ0qZ34krCfF+Fjgypn4/E9Sfednmf8YUQmD0bwy+F9K58nOLdK+Pzi7azWFI8eXYT04C1I9n/K8cclNZtelYeh25PLv50jt82+d8qmXcSyY1einN1SKiqgrOab/+nATYGDkt8PEB/ln3C/P2ZTqZXy4hVJvNvSFllcv5kADvk7PtvwC/9mXtmr0WB7iACvFukbvypvZFApc/ub0XULasxlvU1Ac/h+CTU1E4CAzsgqcdhs2bsvSQkbL3i7RcN/8qqs0HVp8kmpfNPStYQQ1mK2899ppHvlZ/b3RluPB9gFDLCk38bfHNkPVPlh+BjJNHZN6DAUVCmEaqlDPlm0So3ISouf/Hw/J2jXdhOO4rOhX2YQ9xxEy4msCpF3r/FLsldWSCgvutPG+XWjWPKaSeAlbkSQ4SebOPcZCF86P0Ynnhoc+5Jn9HUDcyjBvatGSl5CtkmSK6vEQyUtn6DwX+JGh6wyOALZeZ6/oSRVjjbasjZeofPhbMcwjqFhD+6riifumckuu76A==
    PORT: AgA3e6BZgAO1P052QSElApk7cEGQauSum8uSLSGY5L3DmixOUykHrBBUyDTjtgwaSMDoyRqXpKfG1MLx9xl6g3BHLyCHnBu3ihM+ggeEqwBZdD8bqY0kUTBw08LeBOxekqiCy57bFWAVFWNRm+ihIK6VtwaD3kXBrSCn6DsiVYDyo98ERXeaezdyGcQKVcdLZl0q9MlIRXB2mSkIlcDY9UMWDNzENe6jepoTneX2ouZ/sUgJzS7LEI60UQ7KinBp7kw+HtS5OKE7lquo6km0mYTPt1TENr3nIWImZiU+1Rc4oBGV35bx4pdg48yp+WsFEKBpXDGlYLlGQxgwCqG5EKEgS7Gr5ODM+ZBigkJDRaW+9/NH+e/baS8GrOBZhea1CRsALaBcmtjc2q7ZRtM+Vqazl+i12vvS1xAVg4DEBIlt8rDOJ2nUw1cOMnSmdZ8J1+aqpljsITX6jWWPujJ+cxiZaFu0r1QymURSAolW35EPVDolD+KdUkSUrBosFOJm92x3FcN3NrvM0XLzylxjd54ukz9mHblYVy4rU5cx74RZCbLsrfdiRW+k3vh0kZhk+5uLpE3XEFOQFsKvCPCiUcMfqCw4DkEgheX1I1A1qCFMuO4x7/6k/sNyFHy+RFFeO/y3lwElIjhvacYZmkhEqcuzbeciSob6WlATjF1JnJqXlJOzGCZSfdisdLamhQPYQTf3F5Rt
  template:
    metadata:
      creationTimestamp: null
      name: support-service-secret
      namespace: pharmaceutical

