
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: payment-service
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/akalanka47000/pharmaceutical-payment-service:f286ffeecd2c1e2b6e325918d4513cf7557ad55d-1
          envFrom:
            - secretRef:
                name: payment-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
