apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    PORT: AgBacGA9+W91Xpmio0pXV691mRQ3NR+mJ2bgEYgenR68y6c848nM8be030CKDyvyhFQF/ppl7eTzSAaXqbR/54URXFEfqBbk2BVTYmx8KrFNiYQs3+DDGa+BZuHO0fQVWWXJ6ncYSbc/+/luwgq0pcXkNl/ygA7F/ctzwNUhjbgDuBzZ+NjqoxuBRPPeTuNvF0tmUZ6H67d2pDjVZWcZJfiHy+5r1E8TTWRAFjzsLvsUBvbcvWQHV1asA/FfQLJk7Qx6yfGprr0durNAn+TPNnswrihqrZPu6zJmWJDydvLYGI3jobHqmx6ws5Ku4ZDhwjL87Wk0itLPm1UUCQrmpOwGBopjVp2m1bPkd3aXmiHAimQspXGz6GPQuUslHBrbv45kfxydLGUe83OxxqoUkUwPnD4olr+kTPPI0OMY2dfAt6GK3qNNjSdkRxbU6eKm59N6Y0OUcvQv4gaXWjQoDYfHT1GTaqarM66ZQXKG9yjWesC6NlkZ1roqQBD6RLDQZshFBCYfE740dDbBSxri0Eygjr03YRxca28LrK8N2TV7wULG8QjgEnLGrUa5qBcP79P6qLCg3lKPhVOaGVe3ufDn29XUmrgwIIGa2eRieYr0jg942cfeYnTP4ys3ChyJh5eQmvpkoRsnF1u4SykDlrdbjy4LQLzOPc+2TPZeLjxUZD9t0bXYDflLJrGQCaOtWQ9TLDZA
    STRIPE_SECRET_KEY: AgCd6BzyRkjPYXL6s1lI3HF1UyRVoCGswUMADX3sEhVhkH65m3VgajwiItgUst5kZVlaHD4Vd4PclRo4ydFsLeb/vYz9tL1kT96rch0oCH+KNrYtihUJLLK3jHIGrdwKsNWnCFC3uxAGpZItzVcbE4QO00jzvgCM4o+vFuN1vKQPG8Osk24UO9HEtzXtEtbwF0FrwfOuX2pdrIEM7tgLcBlPD4ouk1tIGQm1SRLPufMl9Mg7RAoAFd8pcLGkiTieUB6W9LyxHTB2N21X/xqXK7VXKpcHCuLqXxf2LcYYaDvEPONOFIWxHjxmVbxYMSjqkYKs1d/aBdoywylbgBLjv4Zak4MBZlR8Txyv8j1GD/Wb/w4BiR+juGJVCghrauQ2O/OS43e/X3oN3aBZFoaajZf7WFD7WXKwe9AgsstqZ8lpjI1wXs3KTViuhUabkNcN+oipqKSA2ekqs2oqJlgelWAR1PiIxWKb/vaX5UYFn2ohilBJzw0EEZil3BY3LBJsWmpisHpChrhL4ixD4z5MnxUbSlUIoiQuGvoXJqLZ9uifINky8tGngP7e9SeOkJLdxc18vGptpENGYWyclzWcVU2BuavmDCEDLMxWcwiyBDtHT95JYVMLu6Hrtma/Qk6SRwlJ5HksWoDG1VnYOjfQ4MxvHf2Kt29maCkEDewikMjMsx9Af51ykR7dLYVlT+xQr9DxkjBW95ouQEGHoOJe8LEUzONS94s9riK2eAFOKPw5d74ptuZLEbBdkTsfjQ4iB3KhWt5trQmOobwG4+uP8CHvuG0OcpawWTgVuB5fxGTTN5Gwavm8NIgdl3FyBSkjsIcfmBlgsBKZEobOsQ==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: pharmaceutical

