apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    PORT: AgCzIIpFWw1iroKfiqwacg2xEx+PZ9bgGgdbht3JeZcNS5KEe0rb/uFam94L9W55FsDReifg+5+HG96BufK3xj10zbbsdhVacGT9nU6R9KAqE2DgDXEajARiVwqE4uP48X8lQPgbLtVEX/5cYxAtcymmm0NrVqA7Xd3d7VlqsWG8IJx16xB4+x0kAOMTsrXWpiBzOqxaH2UxTvgircugTk5FkaXQVBaAN4SzclgU5SekJwHkhqicvdYTjuNP3jWOn2lkOUGQe284o9w2cdpiNo6kHw7zSBj6dwUO6b8gTrxIhoJP48UnqGvTNX1+SxuarqwPlpiRhecBJPeSJLIhsbI4BRJadJG+fcKEOLHrXI6CJhMU+raJUpHlO7EXXT6k0FF7QPv7NhhVEcdc1D71dFeM5XRL1Kh9fuuKWDq9bIQRGede722OvI0IWXDFmW7hXYxJVPNjw6et4Am0HdItoCuSlzxhTS0wGuklR/Gejl1f+nG6HfqnKMwEp56T8EqQHb/fdprlunL9D7HyVPPYgWrwrEEZGLp0ajLq5e8QzfrVf53juCPXp5BzDc3OMUtu+uH7/rj7cwjVM0tdhpqdkQWF/8E8w7YUIczJ67qRaJPNHZQA2cRcCR4liPAz/MysldkY8wuBs3tXb/4uDAXGt7CDLFpDOFvIIsnorjdJZfZR8evT/+NH2m6BoK4mJnDv8dAIPKki
    STRIPE_SECRET_KEY: AgBqvuxhOgcGWqJuV7oIIC0Sh1HDuDZpm5FzrU5/Imx5slvqLe9wn06BuHj0EbJdRtPucvpD7or0EN4g3NOKoLGiLxBtbzQt1lr0dKLaKtqDX4/39U8uQ07qp49Pw4Vgy64yag2+8fx0wzbOlZB32wH8cuZFFU0BXdi9TsO9ofkaC7TH0XU4PNwho4vRuEVWtupC39ty7yjf6Wbpo+roSD3eKeRQgkJ4d4F2ZkiU/GaVndG1EIsPgfUrR2Em4lg5FqRbt44uPiv5ycSN1Hge9u3HIrkopO+LlpZ3Z1JnstPYaAuK36g+/7Qwq73gv7mK7BNN55Wjh+zkZZKFDd9eucMPm2OA7vTbDNpBb8T/QLh0deNogImo+wWihg1PCnXpbRI6Z79f+/CM6mPrsIuwTh/X07DagYNIKCrKs6nhp3TmmBVBUioj449kavtplacf92ywUSzbEDaBQJMyYxaHAHCprACdyno0fjRBxVAkhzM8118s+BpHw1s8rm9pnOaYE+aHso2xZgl2Vd6dpM3/av56JAPMbP3DQ6b/lLkYvQhxQBuIo6UhS3POVBAVhM7im5H4KvybAGV78rjR+ZQCeEHZWEZbEo556/5Ccr96LL8X8SxxxiTp6FO//HsZiQuNGsRJzyIbfSO3uiBOZwYg6xi97Rd6+8uulLGxskyO5QdOM/NOTStegMStMJN8TOMBGuoITPLlsp7egzUIbfh/+wriaKPNf4FEWsiQVoN7oPx47xnhieGsJf13kCxbFeUL3qSE0vFdQWo9iDW15BnFjSABDU/rITucM1eEpojvcQzm1ZpkpxfHArlefgbCVD9KTUuklijjN5d+WlQ5lg==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: pharmaceutical

