apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    PORT: AgDENtYJzsL7cWaV0XJOtqxw1ZTr2HBTvEd9O36jzrSSIyCeMUbGhq3lZs9jByZV5GJ3h7hjuylOiEQ/xHiLfyd+VKPlNlHiuo/PQuQdirv1m3CJbQwF3H64z+V2gP61K+izKtA8i/KVz+1iI5sOBjqr/kTarmsZuJQMhB0SNnIJt8W36Gg1lS6h+3tx3/QnjG6kqljFgaYN0T1hkFjCmSLVPFVp8aFDs+mWNM7oqbbmtwOLejR3lCahv+zBrY1nnkBYx6xsCHdrYxCZD0jZ0x8YlV0txiq3uCZlOk2dhwbGTurc7wiE0ANCWK72tPaj/OAb0qdEyA2sNNuZQt6Fbe3YlAjWI+hE4GhaRX8cKvgyMs3ad/K5ArSjaOTYnavDEriAFsXXhEGIoXcvVPNMLnzI+U9/cIN0Hr/fFcovEAYa0MSbJzIobtq3sh5WpqkWsWMi8KaDVqr6aBU8YQoJ3vSU8ghz0qvYbhbDIiklb48IMwcKdhjujCqHymaub2UsPUG56Z24MxOkCjazJPrEhmQwElHyEFrSYrj7em1xgi6HnJ6CRBj6nn/4pbYQHdLgLTobXkt1BdRAMvj5J19VSHJf9l6KhgQ+OwHnHY9A79skR7pn+94WNKicsARvIkKu1waoNmBx5Tj/YYcJ2/WNbCEv2Uaa/0cme6OqUBvR8sJGc0Iew/SOUTDDJOYiRRnIB0gq9a+q
    STRIPE_SECRET_KEY: AgCQog8o4/ZS6naGc0ChmHRfpuJDsNms0kEbC/rfAyWjktbKJTkYxM6rJYN/tnJ6H/2Zbm2GgGulP7SHh2BnHVCC94BWijqM2BAd7+Z4fgUcb5IrwYAqGalYn1XURj6vyhuaKbQSt5inPiW9VlUcpiea+1w4o9xdFrsaCrk5f1fyI19uMllNovkR9gY56e/SyxK1hFlcyaQywlT7dKMpS5EO98VkS5Y100S34M0uKAegtv6b3clBA1OEZhWXDjLpNwnHKi/FFjsYzZyXkxx9gg6pKiPW3CM53/nUP9p3CkAVmLvZUuGSinBtIxDAdnDv/9Qsp+73vNGan1PXzQofO4jYcSRvwC62I/YjfXhSe5CnuGH6SiG7Xwsw929RlVgnIJsKtT+RQFS2elegkD4H1KwdUz3wpY6KH7v6ILjiWkJvLsmAmyv4RNDJwrmVlu5Y2sO/t9I8QRHPN8LYqvxX5gPVa8th6h9ASr9SV3Wwk2kiabp4Tz8Qbw7UppAK1kmrGtAgLHwt5DZwj3+8BwnY8PPAb0tnXOTPKLr3Vh+aUm5QeQKFRe3lZ9z06a4sHFIgG2JHNherOnNDHno39/lysLAEJn6xFJoGTZb1qgWlEqW3GWB9opYdtLthLQmWdgC50jw4Ae/W/wWoW4uFDYqkXV3trw75Bs6Cgxv1gSwyLG4QCdLzTb/WgR6ie5A13xFPT7oKlgJYnFX9ejicyBD56GztsWbiD85As6CiVPF1Dg4QQDU5A7IxzZfUMc9VuHRUWxyeR83Ru3tobyqI5o78JZ61sNu+c8iplz9vMg2N89WD1RjtoyISq9iYZrAs6DbnSBeFvbDM1f2249rhdw==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: pharmaceutical

