apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    PORT: AgAUOmoL9/GAOx1UMeeb6Co+yAaApfARSPYElq1skRr6DXgqPbcDtnZKpGEaQWCUaDVE1OFqNXc2bwGeNsoK23DwquJtwHzhpjSskJ1oQRK1tWqqHVfVgRUe6qjlmklhp15Tuki9XiCi6dakBNJZPY1RBq92lk6Bz1dqnDEM3AO3Ds/ZYNd+Hpkp9A3Bg2tyIWZ+9GZgj7OrqLYNxvYyiZG7oLqheP28ruo4KRZis8ToxyrH8D4SdBEL+QwV1wtZRZxvYndlYORUJYdBnTBPuCTiHI6rIIr+LWHlzfni7MTuzYYmOGjqVTDNCn9tJ4LpKx5u8iBvVLc13GHnS3RT312xXzKdTF+ubwu3hEd+cOO1VE1OshIE/6OUq01noKHAd0VWl/QfUFWDoFJmZJmhewTWIbQmvh1d/glt/MFnPYaGDQAVaTGSd11EHh3owNkNfaV7HYmef2lpo6O4nxHkd8z9j2dgIr68pBN3qeO5tWJVtrOozUImdWqJcD9r9TU6al3YCE5Po6JDfT+5Q+OFNjDseIZe7715Hqcos+zFWkF3XGZpG2ZJNKqZEkGUwOYzj9BaqZDQPkA9c7x5hxVSfFzmlvmb6mZrFE+fSl0j1ys3awZQMqUCT435KAi+3n03WDewRmb+Lozo3wZ/jH0n5N9fbZh0Wu3SLrd45/jY63w00BLRT3lXlv159lpRRXSRJLBgfMlX
    STRIPE_SECRET_KEY: AgAmvXlPL3oSzDMF0RwuLM9C26/5hyeOPX/r5uaFeVgyYWATJqiwX+/rzDIdETItXOFB8yBcU+Ovcyg1qb2RomZyih4V+MoagJ8BitmBXJUimBlsC6R2IYn4p1GaAhJlzVlhJGosENOTJC9NS1HExwTj0bLBYhyyAjeeumzy8njseSe09UT4Nszx2UXNT4KS+6HoVNyDhzumFtTScL0TSFXE1Saw+foHAdp2Apo2/Q/fevf+11+pvx6MLHbpkWKDsE7xcKZPMumQ7Isekyrt5bTDxBS1xLaTGkYYOeNpf0rawZe2HWVNhfiG0QP6LGQgTEs/vE0GhxAKq97onbzsVqIu0PK/a4Xf7hlc5uwNYswVTd0Hxz50aZn2uBHO0rI4KxgQIvY4vVmcOODR7C7g9lfUjM2Y/m3YBTGYNX6nOgX+FZLAhMDsJclZinOMl4AKb/CBjhWeGt1dcnv/1bKvx6VKPo0W0NHEHNvJZXViD4AraGifWIR8W5VWL4i/uuMUj3+KcapLehsU3IPSwHpFo+pi/vIw4a9Zv01WVWY9bO+egCvYW2danMQrGDUGC5h1ZhS3aqh81aX3uGwP1qAEhfzZDQ3myP9QDrILZkSTclbBnYdWuWDsV3UISpOfWNSGFrlhafebLk/a5kT+sz8kkooEM7kei/dkdrgsSlD0o/brGI+HXXd4JN/xV+uRTVKPIUbn20JvgzKQRFBXd4CZYO2ePF04XCWJ1mw4HnWAPmmEYyf0kHUy5DGPlyDUaodd+vY2NTDD3FFBklpHnNQwQ4lf8W13Xy9S6x4/CyFMxw2BJChJh+ClMNd3hsjwWMJ2DTrNI7w86CJDhm3Q5Q==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: pharmaceutical

