apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    PORT: AgCLh/EZbQqkB5M/leFToP5CmreqxKdmkjPt227tRyEy41LhQZrjbv5Y2Rg2A9qFt/dpeVoMui9XO9yKIUdEUqkJl+ov18kx9kXkABGq4tjSv7o36o74NkzxT+MJ4vSkvuAHDXjSgqps5vk1boBmal3hRsKSpXOXOHXFu1yVenf7WZ9H93XlTPIzq/XXpGaLi7mdODgpQK7QhcUWv2DGyttiye1uC8yakoqOT2INpfvdDPEBVlWLvnHiyyv6qFlTHVWEelVeZlwNI98bKAn+wMOzgfChbCDkGMhQe/ZWU+7FVXXQbeSA0R0aWkaPcVe8t2APg+129UBgx3tA+ikN7+iTNLcKjDPKb3XAvRC1t4MmzGnVnBGxB2j3dXfu+q7C885josUAfeqkhdCR5BsBalDVvZnkFiH/kH9m9IMsn9aFP+xIsYWDWhIXjUXBN0Z01EMd2mM1qwOlxNOtYgYLE322bZPA4soGpU/MY4Uli49AFRR1Rnmph4Ye7CBFyHdZ94/8jeq/Dvq3ojdOaNLbasb3qrhxEf6Gzo9yyxxWnK18J3Nxd1xtM76vmeKN/l5Jy5qG/PDb/FeEk63m0ZC/yunfsp66sRzpK6ubjUFbtl3p8P+Xe/zP8GKTHV+lI+thkT2T30NDztfP9FXvIr/20FCMrZbibRCJIYnfyt3dy6IjRCBw/TP4pxJyayGAyywceVm3iWvp
    STRIPE_SECRET_KEY: AgCxEcrc1/v4WijktJWpgv98rWapzI+U/1Lxt6Z12Kvil2aZkbKzZG/QAf/T32Zh7thBL5rfODusKX0oVz9ZHhHtFBT2aSz3s6czV48yx6A/ngJKPE74lf3Urk6iQVaTRIzwEyr2J9Eg/kMN2XNjqz6mS6WSTv5h9mLP5tLjAv3W7Llj+UhCt7igxyKHyHEJq1ieNyp4TzRrgNf5fLghWafl/cI4M1zLNuG6bGuzwZva7GO3SYYCj5GaNuQDdcEsdjEDzooU4j7T0khtrOdL59A/HeA7dO2YRvHVi53K4DXSX3ZWoE9hCmKhscez7rmB+tLSLesN6LpZXxdusAP8uzgCag/VPngqi/fKlIIN1jqoHgupg4tgTVhxv3DDvgeZK02G5LSUKYx5wPEpoRGdJ6KDgAAwTCDGNNg/pgUGgp3CI3cE9jn78ar8u+iDYLlbGlSnJ+pp7qNui7rf5XR4+KtVztY9IBguLpzXygNMqtWCeA22/JnIwr9Yb75KxMhcj/NpQV/qZrDJCMsNK/ZNRMpqn1tlkqF8Et+EUgH9h9SXJLSakucvnpS5Mwzml14t0FxINbKSKQ4/o0sVj0/MabYpwjsI0rPuMKRKSM5CdX6pkt2cCDZErUl6s4NNLcPxQlc67ztNIQsF/CtpGx5CGBm7vkTJGbYpZs/+1YI1mS5GxjOR3a4JppbNkCpZbYE76N4mRFE27MzQkXPr
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: pharmaceutical

