apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: review-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgB7r9anjL95V2bHFQCQZW13lOy9auJcERO9KOdAksYSGBB+oXEWvbwQI5wPsWjRH2rnx+fGN/26ftFRkvZRWVbzyXKTJrcRz/vrVBuSYVXBo6TeNy6Wret3pYa4pgD+PEXPcfaFRR2e9Ax5HUgNzPgFbZXKTgyes4qtwW64LHepIGIj/wv51uZia12hwgvA978ezep5h8dTtuHDcwtMYn0UxZh8HAw+Ald0RC524GcijHxBmjZfQhFT1DZWLM3Kql+V/vaEW45phobY/ee68w9SeQqR7ihDA3ZJKA8FdeTPMIHhKsoY5C4/eJnJ8liarGSoqrrU1Vo0SX7W2UhSVjEYliELDt9h354tdugDpov38RqYvjnORqGMfFRPBRcyr+P4z72Gie2xX6WAIqZoqn4WW4gVaGblzMyLvsPfF4hTr0lcWmAhQ3QKeo7xeJTZ5wbv8kp8SmuP+U6UGwiTWrSvIIzi4Y0PKOQuS33rURNr76BRbwz+2YrpLIU30YY/JeZZzfLLSHgBAxsanZ1BN9xf73nkrVs6vESU8Bx85kH60A69PlEAyfZDwMK5CYtj/37wUt26g327d/KCi65zMpOadbJM5WxQKOye/MUH/9HGglmiBM1UWEvL0CwsD7Jx0J99nlFj6kyivtAMAtqu/OPFKwi3Av/AwlxokKfGK6f6q2fuwuSowIU9yauYQmHrR1KO0AFcJRGL/biW8rwBxqjt72kV3PtjclTIcVtAFdGeNPYK5dJhOE3L1eiXTBDMuFrxg/2JfWP4F2IxwAKL90d+wEQNBcGfc9axAf7kBZX6tfjNSuO5huwMmOFiQA==
    PORT: AgBScPTOS+ofJ339PVWBthYitwgVr1Nc0s7FCRoF1Wu491PfRLx9aXdeaMiOTlllaguKgQTzhjgZlVYzCqpF91Pc0/5bHwJo9ZGWWu0KSKm7R8gZGKx9N43AfiLmmyJtCR8raM5b9xaJvoeS4B9uUOX46YgfDfzFabNTW21+CciDBR4R0Lg1UMVreHYVX1BpxEVWpXROvys5jiRGVdP3bxTAizSdRZvYdtjddMWzPJbQO6Q2FXv4YxpVkLB+7WfEj6t57x11YYOPZ1TS0VzGFpm7QMiRYON8emvpH8laH0V0gAqdR2EtZsMJJtX9AQwrvDfNN34T2hZOibcUuIH/GrzY70aCfGB0KS++Elan65IOHDlo0OAdX2NaW+mu+WJZKvnr829ndLMKosHdi8Y2b1dx6PVoXnX5akxasNgylMaVCQqOonQhyfYcXRFgJGJmPId325k2i0jzhJ886CNVx0/ZdduHJ7c10pxRRlr4FZlbauQCwaEwOhB+ze8ksdYHQ7xceOHUK+iovZMKsmulGrsIN2KBgUmlgCav1URUMG1Y+2yMu7Br0W/lau3JiLtjZX7jLjlfFuj8xzrBqxEFx+OYCAxL6PUffdkWTIF09JxQ7fjkwFNC/r4btr2nXwxy7gaz6+rQZwP9SzNLLBD9d17h0TtyebI2C60+66RUWbo5+SAIXT90508gHTNZ/cs1EGyMJ3+4
  template:
    metadata:
      creationTimestamp: null
      name: review-service-secret
      namespace: pharmaceutical

