
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  labels:
    app: sms-service
spec:
  selector:
    matchLabels:
      app: sms-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: sms-service
      labels:
        app: sms-service
    spec:
      containers:
        - name: sms-service
          image: ghcr.io/akalanka47000/pharmaceutical-sms-service:811b1ebfe7e5218885ddaf270bbae835948dacc4-1
          envFrom:
            - secretRef:
                name: sms-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 256Mi
