
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  selector:
    matchLabels:
      app: delivery-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: delivery-service
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: ghcr.io/akalanka47000/pharmaceutical-delivery-service:8a403623d7020ba927f8a485ff902379d77ccc40-1
          envFrom:
            - secretRef:
                name: delivery-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
