apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: delivery-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgCChEKeF2ISB9O0anIbOlSG61sdtY4ZQkMLa7j2GM5qKwHYpDU1bjFCU6U322AWm3GFx3LsGXhbkHfalOF8fWxrQeXWCcqCWiYC8Th+lSh2TNxuuoGf8LqZxSsoD4dcVjtDr/1Qi1qWrOP2bpJMh1TPnS72OwM7cdlbKARJorMRIc/BFDvd0pJWKk1op4xbt5Nf29KxX8DxzvJv1ny7vwYyZ526klJmG60aevpX6cnLhUP0RGfioX4BbVFu++7x2pcw5Bg71VLxiq9gGDXb81q/sm3nb25DrrUujSv0/rYbyWhlBwAsiCcETC12Vb0RgU9fo8yR3c3fk+WQJmlL8tQrSlpJwfcnxqw01tfAgHb019z6WliB+aqoxDfPt0ACBlCPbNE1L94TdZ2e2LY7ezNulO0jqDEShFRtiZfzwGTUq7XO5fAUlxkUdDqsaYRFTC6R92TGrYBS35B0UEIDbPHOT+/tSHd31UJ7wP+phZhkCDBiza7Rx5sbqDC0E7wovn0cbaDeXdc6yKMSREgTJTzn1rbfNawg5I6O+o/MM5hZwIKpU0rgys91RlJyQsQgypnG/P2IhHyk1YpSROQ2hSb/UFAzWevQc8a0PExf/1vP2Tc4sltlZdubdyBKamlN/kFRpsN6Ix8mAxGBt5bxKO2hgexOKg4hke25VwXzmJtHzi9s6JjR/A8buP7r+noreIfZcFGlZaUsprpaFZVhCaxMiNgq6gi8cCC1Ew6yybyuzZnK0PgDBSC5e0SizYn2IyARopqH9sY9N8FlG9C3CGO41A75olcY1UNGmoEn5n/+LAsQSLCeXiwi3A3O0HVX
    PORT: AgBKBlR7VO3+3Bfmrj0bOGwU0Gh6G3DeJlq396bI/WewQZAaqAO6INQA0NOr9P2gAAtzFjpgi5e8gNrp6UlqR6JBVIyygmQl16ksclAm9oX1h0/b2WCF3Sl146qUTcfc/9M1EykLxRi6n/H3FyJfDZftveE4LeyNUCOfT578XnD0xwONxqZXtAl+yET+wymynqzDfJj2qfR+KhCCTrelU7EC8BqHVqYPLYRPt0YHzQZ1G/RDVZCf2pYdlTS6Qb3Ct5Xtz0IVq7AZ7L8eus/r0wVdm0S8Gm3cARMYzxx5R72VINn5i6IsqJ5cgN42HIzfn/FZ5nYqkq66UUeD2TDTRhjgmqZOlcruVArb+WOCEBK+vgsX495Xr2y+CAc40+JCltTsJP38fVPY8l3uT3+VxE2IEZeTUoL1PIh9Wbi3oD2NC5CPpSV+OwMVNTywdaEy/cp1r5wk+32Ed3D7aKwRUYD1PsOpEnMAWD+A65BhOWWoMCBGbw2QubN8PFQWLcn+PgHbqf4K5ObLl4NH8t5TaiJxM7baSEPKVWLScFFOHanu4jcRG9BMrE1lr9bVPamdlMpnaLdGKPqI5iUouVzJ3mWDcN2u3wSl1WtaShDtT+KeJChE0STRnaU+g5puY/d3BqGoYUaeqSS0gpAu3oOou/m2d7sGvC/lrYyb6uT7b1XuT9u9Wfu8o5rJbRF50M8mWCBcJ5AL
  template:
    metadata:
      creationTimestamp: null
      name: delivery-service-secret
      namespace: pharmaceutical

