apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: delivery-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgCX7Mn04rYj4HLTjJ7bzNFHz7NyCdxThjeesx3FJHqAk3FdcffTrDHC17bIaPmR5VdqSb8z169TMGlbSf9/64DgdFxb/4FhU/sHRR1rjN5xqCIcbJCxFuLIXi7pLy8Kb6VqwhhDrPYlm4inSKc4/dHaAwZEznXjbD0NFkSSAo3bkZg/de19LeGBHGfEMuiE/WHtL1oG6pBEaUCbXP7o5P1tgLFm3N2HF923MmA7Qwn8D64VSI1+YzCpIajuz6U8lMHwIF4HbVfjjeSRuuCjOYPpKv50kAj6gszhvX2sAoorc725WSm7pd8PT4UcV9s9Ic2Kyl5KvRNXnCcDsXU1mHRI8mjbAdeJAbUhgoNoqwKklC1RBH4wD9YdtpL/9OQJnXI+f7P1H1yNZneTnwRlZuITIYV7zrPl00SO7TJkvI8CFdVfeIEDjGn35FoslnQOkB8J6dvh4uALCMgSANvnJvpMYAjNRuj4OwDtlRuRlDsVfssxMkwij0tPhndxsv0JIcYPon+6S83JVX8tYG9gFco2bBulW8DuxJ0xiysr+wvHq5nsAsW4tZZ0oJFWnRV2SVICf4sHzRNztNdYUiWhrfPQ1aJU68mHVyCuEqG/z/6okq+LiVSjfOVOXDZZn+2pRc5tVP3mVDyqpAaZ3Sl2MafWQg8F/XekUhHnSWNN4MSkxfrFTOchJDV8JmqLVAP6md+iCmxIvaqKyVEE3LJgIJboaQZM3C5V9K7y1vIQk4NfTebf0A4q9WmfZruDm494dzJsXX5GifSjNOVJzWDLKnexvbqaX3jKMGh1Aw8eoN++9foZlNONwayHCI+6i36A
    PORT: AgBCA9PNjs4IO9DY8MR2blEzHIHsDu+cXcyEriR8giWZaHzfauK1Lgbmny6zyC3iU1BmLVoB86DeSu7NTJCfQAEj5wg7tZSHmbqyOGMs/tGQ0ROtn5CMCWjjvAaJxyNFWnucxCtGJr16hhvoKiQfKo4xc4ur2mpkhW1AgPx5Ygw1nFjjxkIpp7toa5scHqWM6CLzhimh4Ls7UZcm+z5IK7CwQWPUs0u/todTn8PE9tro6ZczcMQAn79JKLGoGl8l0C1Znchoh5BVypSrxMzK2/xJxHOcpyd+CveWL7Do72LREaoIh7LBc9IlebV+9/YrNFBZJrtaeqc4V8aJlXEZV28llcDImJrFp0rmXw46tIaEDiWAGrSuXdj3r7huwehG4OWdNdN1mOQSv3ssiSOFZm1g3dC71IM+tWk6EnDxUNgwVDHhQOwxBxGnT6yzCauOkLJZgBrTo3XhhZZhXTWeAUher9F44cbHi72iATD5GRi6Fo2ruJSxGh0YCmQPRaJofyPdjzhP2EkhOkDGJmzW7Y1/xj2M9gNL4phJjRi6CbSOic/TatRd2lYGFfePMBIo3M22em9lMHKE9x4dns775JIOSU8pN8d9Za6ID9VJPF1Sw4r5yD43FPP8Mmp67VhnqCfUSfQ/Ybo8OmhbQIxxQPNtXD2NrRZHwCvogQVB/29/IB0o8IzTtFz6P7TIt+N5OYe6q81m
  template:
    metadata:
      creationTimestamp: null
      name: delivery-service-secret
      namespace: pharmaceutical

