apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: delivery-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgCJi08tsNWSD15qwND7fam1o6aIL42yxQbb60Z/JnfF3GiLk2eiQmHbC2ARGFwwzHDZ5iCJDj7SQW2uSBwPCrlO7k8ZaqIxrWc7mU0waWbHLf/2kJz8qQBlXI52YStP1M7O6whBkS5p0T1Vix16QK2OZNun9smXut6rer7A0tBBKZzxgM7yumE7adMs8raDNv2qlAT2ooa1HaAkiJe/uT3RyDME3Nb21ZupIxqPG/xKzQa8ODJL6FHM171Y3ZcEE0S5HC9JlsYtTzODzpE7LdIuI15swXa/K5iVO4wo39OwHl/AKEwZ1Eb0epWU74Xr5LDZSlr5KyzLFx8MoOCPI6fugKHCzGqHtQFxAD8+jyoyruADEDXyFG1q2iL7Z/BlCMsqWY4x2lDY2Nol+Pf7MoM/Qd0fCUB7awrhrH6b1HUWmum0OgiMSk6jjUUmUF5t4I5bO4qnx8rqKyxp9+YmApwl7U93enkJltB6oBoDTayHHnCOM/aB+z4jYAn8h3qcXJQ1LPT4sztv5GGog1jI6Y1cSh1tNLN1DJRQe/Rmoa4vNUVtgdS7VdoOQrzUEvDwx96bacB9XahmycVyXwNqeQKZfcQT82SqrQ/AXNlL2oOe0jycsF7hNe7nXolP6iung/tRHJZVi14YzaJ2+OrQgyN77PaE0Ag2K6LtvwzT3xLLMl2pYvBoYTyjVuiIaqW3Qe+Kdevp3Kson1Z13Ht0PwVTCOgVblJY6xeWHamA+na0TtDXkNdmhF896GF5pzdLSqMxRjblrTm+KEEUi3lH5mHHvmMBcYErxieWv+QWAr+BgMev1oxorP5v2K+P5BZT
    PORT: AgBeImxQgGNi4s6uttDA9yjCNx9WAKXfARHPuYTmIWnKNYTzI0ypKkhshU3ZbClibXqNIFTME4uttkpVQJqbetICpvzfc9GPLXh5DMZ5aRlkZQliCrdRG+SHS4Orvhd2zEhJSWL3wSVBhi6bmId0ooWKIEsm+Ffh/6j3EwKCDKSh2NG82MzJdcLZKydCgF1Wv9vfOKSpWxyphrvSFq+mc/UdidJHrIoIbB9c4oFLWQKpAnRflRgSNep25YaugoggDECYEe6tnhyIkjM8X4CgJl2JA81RUd6X0Z2bZ8lYOBlKtehydMSudpnkLMQ2oOW87BmtGjrVl/8VobfWtT9c/cAN0neSp33HWRIMw8R7NCIQTv37iVr5a0i6cQUfgQ88VbKuIFzPCswV2zBXaM9Lv2FUmnP6vvFTAW6bYMcMuukNBnSOyE3/Q9BKU6iWOMqwpfC6+wVdfYYInLbT+aNzYHCQ2HQW/Sln+uhMxS3HpZAfmCyL2F4RGtJUKiehMz/Xvs9/cwDr0ix/1AOlPgsI7kgXgrf2QSe3PAED7Eg9b8funahmkaLOGktwMJCVuBGiFS3ei69rF6hkPGAl/97Jp40r3KQ1ekchycm/Z+U2VdFd/9MmjYSwhdar4t0dzNgqRnesbKKM7+uQOICqNEEMJ+eBwkkN3aHwmGz0+t12nz/zm0zT1eXDdkukYCf65clkLKlmGia9
  template:
    metadata:
      creationTimestamp: null
      name: delivery-service-secret
      namespace: pharmaceutical

