apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: delivery-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgBaZAV1f/GGL80y7eHbmLfUMwXHwBcpC2wpOjnAJM9VpRXh/H3xD9ToB8ZW1M+kQRMneCO706RsdK3ltyhR/OWhxmSp2t3vCYQS04utCEheEfRJdPY2pV+sl7wtjGj/InHFWLEb9K97GxDQnXX1fFS+VAvwic8zRTsm4CwZlaxfMf2k59OUfA5NGadAfhUJCeJqJRpV8UVz5L5mjpWHzhjXnr1j6uAMxdM1obtOQt4LcT782+QWXTOfTkIjhTjLOfWJiJ6cwgVYRqq+wjbsQodoGZ7tjxTMHIzErR0cTksetgglhTkKxwv6ttsgeYimWvXeozKWE0au8VvNQ7C7sXlDHi2b8ezIRjy62j3yXl+V+PyUmsadJd/LUj4jmki+TmRzFmvnr4ivIk/tREWXv0d/gf7cXQ5kLTNYhIp6cuIDMEpAXkjjksvC648D15S3tQhYUBab5o02UuyN4ZELJAMtCWOIqdbh6937idCczG0fdAacj+a40eXR+pMYVn6gN2fKzEZz04cA8tE/Sh/tWmAhegQreUolaKF4sGmwgbH2AbmhrnADv/2XVlALZ+Lgtui0sgfqnG9ZOKxIwUai6DJrIGl35WXRcmQAH43cmDC3y6xCUq+xPEldEhb/E8VUphcfGMkNSNGTPzlbqdTyw0TK2KhoGm/CG6o0ZfiBSZwR+t0Gtc+Lssi7hmKO4Iayp3M8atrduV+TmCApvdcO5wBFGyZxGfrk7SKKnWyNofTsLdNrW/Gg3UtLXPuIh2C9t3+r4M+crL0sAwpka9AFf9otXSNxe2QmewgFxOrgVCj6nfZPX3dGKQX0H39z8LAn
    PORT: AgC+wG3HbwK7/1t83jbJXUhSIkLmwwcSIt9iaGJCKjlosGw8681AeXhxXeie3cPwVZhPsrHQ5h+JN2WuEqE3PSGXvF/waC2W8x8LcdxKdNP2tBlfiGDpRDWW9GYxjWLKikUhBp8BBWh/UB6tHv3gXg48jfqMh1KgLe2ys7dCKuK1exKx0SYb6GRB2g2epVDxyVnpe+mty03qWIW3NcpOTW5Gclh5Xt0LQ9TVIP4ksNdYoGZ1ey9NX3ZtLuH1eOKtnP/SoCmKl8YsThcue1RdsD/Yve/Ma3xMIVHbM8VyS6qCi5tJ9NLvdFVqxQSzyDBk7ORgSVcHlMKK8Jp2Bmw6AesW9cWIIuZ3ooHKfhEpmS5Ncm+WbLvkEGGLFQb84zIDj5pkUAkN3EFdLtTJoURSx7MK1R6aOdISn92tgz/cdVI8GqF3xaOA1tQqV2pAK1l19AAQZMPitEV9c9V6xgJH5Jv3Vspr3tXLM6LUwjflITSP6Be0pve06pY2eWDrmd4VvJUHTQv7KXd1AN6hELnG7M4q1XYK5BEj3xAf6E3NCsYfJ5HV59GepxYNAzLKmv4WgUukAlrx6mBXRBkjr7vtmZsS3YzuxVKgU+HDhqh5Nr11BlBkelpQZTau9phsLBJBcnsNzpWEfiqb3ydQcqfsWmqbpWru5EKtyetIJsw5ChhcjQB6fqO/yTX/2XlyiFDEJs49QAK1
  template:
    metadata:
      creationTimestamp: null
      name: delivery-service-secret
      namespace: pharmaceutical

