---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgAZhQlQ4IWHamHo1ScITOzo3g3wBHdFbRUlsOqwQZwlw+goGnoLlZ5ub7uIvMTDKomlMyTEtcyERyJQBWYrtz6p8oXL9LOWKGqxU+0yiwPAiCy/iov1DAvpD/L4HZ2ay7A9tTWh5PRH+C4VuAlJXq65YV9An7oZ3dJhLDt6XZTali1d4y1tK3pwDPhJPVyZLTx+TvploenUrJx1oRgxdKXvf5YxjSXkLnqOQ0TDtUoE5u0ZmiddTf8B+EWz0Em+29HSJMSGyWFjsonDHolFfOfqxOO9zMtvMAkD/2nQcTTpIa3cMnJ6OnGFWGlcpOMnBLMHVe98/VtmCW6TcT8uusq/PHwpzkVMS3s5TNYoieA31h6bWcQH+GVXseiN55tg6NGQyNulmsTYgvSKOygPJJelWGFB7sJGimECTQ5qJTww/EYR10iMQ1LdabQySwwQr1i7QuL4yJF8xIzQrv/mMhMUoE7CAUICw7/qkLVwwg5/E/cSN3cnmDAdnwOaDmI9mHInxGeRReoXkis229MPQ4XNdYpFFfz3Ect7vJbEsqLK1eM/SnKLFXf6WtyHMdDHFdKxYTQf/IJF2cmHhPJB7DtdsiBdDPZ98E1W41rKdAJXu8vX71LEMLVNDoYxv2OSkS+3/NdqopHtZzmhaBKBfb+hpGSNnUQ4ioUencUo0AKZIRM1nxyiD4napEK01MM6XjFhRwBjeYkBVY966pK6m1hnUxDM+5Jre11FcPCjuXespETwZdZb5Pcf833z2lj+H295L0mtWdI4i7g5kgq3Au1sQ7kpI3xw7qXWlwRjg5QGXDU6r082Shxkekc6Dw==
    PORT: AgAZ1lFeS249g6FeJzZ5sTP2rHWTXxrsSdqx/PPE/6MilpL5ldoRCyKBmsTEcNtmlCRS/F76nArADOroT4bNDoz6uYnRFsKSD0P4MUaM7fpguH1mMc44tWfJgTccPAglu8vUq1ybzD4JcadNWFBXHW1MYcaF3sVGmkXZ037+GF+wRcfdSMKYeQbm5kvGEVcp9MUafLxsFsOo3jkcfkIDFzVhSYzZyKnJQSzFSKXvixUgy7RuUhrbA61TjnH7o6nLfkUN/XfdTVt8GLs/SH3QKAipJsYK3OWwIDD2x3i/yLefAKOCG0BjRaD6g0EcEmJDCsCpq2wTqpz6rzr2T+pIzbsPvzb6BJmezkBpFn767h+NDXrioz+p3XFGD8M0Wq+r2mVj+fmceP1Wyf/Hqkj9oC69Hn7KWzRMYcsYBVEx891ElBgetoTXNtoUUpTxT4fkL0XQWfIFP29ExKwhYAN1fxn7a8GXbt4j5FJSlC3pYnO6mNIhD7K6ouJSG6s2a9qdkSgb7kAskXOW4DlNcp44+5use5LFKWv218ljuz1Kp/CAL4NhboECH0FZouB4nFMryFnIz3sAHQzle6XzhgmKAi52NEc4VJyGP5t/z1DNW90Eda+zdW+WFme+NnoLG0qnZqAaODGKjH+qAdYU+ISJsuNCi+zedNZFt7C4om32qC60bVsaZ3StEGgqZYATMBbZOQpyhAMX
  template:
    metadata:
      creationTimestamp: null
      name: admin-service-secret
      namespace: pharmaceutical
