apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgCvsYqcwQpXx22HrqN9AVAvU/6mbFyKzQAOAgLAn1T0kc3PzOfm/ueOERiF/XdcLmWcerV691eidmRrVT5RRtq5qkIF9U/aGfXzBTiD/FOzweOq8fRZiF/pBNqtLG3tTOrkL4FcQo0BvuQsHLGrNsoeMrjLk7ZP39cR+OKoF7gzFGQgTv8vwSYJ36m4B54yh4RJ3f38Lh2EdHcEKTDSsBZe3SCkCbm5cOsdE1Zvr1xOZHBxRodGDWi1mkEAIZu0k5I+Bbq090btSAUKCJRNsRREqyJa5AqpTHyckrHCpYcYVMWgn5V0RAjSHYFgw+eSpCsOAsxPwakH3PoIBOWtF9g3ix2cmLDuhHS3Cz3qPW4qS2MkYOUrzOPkJ/KKfif6ZIfeXn0ldCqZgt+k5/TD6IQ6kCXHJBxGUbK2opBn94zuHr8qpbMtWZTtIoBU97Ac9PDDMtD6kmUny0YqJcD6u9UPfEIHmjYSOGxICLdUxZ2k7lEIf8h6K/XoClC2rjOhlQ0vDIOkAiRkKrIdpFCiaNJyy/fOmmAk8J6KLUMFgtogC3CFOpjC8GClSjHecHSiA2Cl4bt4njsKWNk/XlFzTT240LOgpd62dBKwlOfmFvjBJMXHF0ygQ9KEsGk4C6SFpdZ3RBKIgyEHR9yeWBLltEXCSYmdJJbTyTv9JNikwsYuKGePdQfI1jU2Bxk8xCkiScbWZ9gdXm7u1I9OVEldV7Zvmb0QtZDQaHsBOr9ac1rNnyPVNXXrFIGSyg6HItGkddqdmMRE+WuOelenls06JVJXp0Z1uJOB7uAguGOFce0BZuiR1r42/SkFtGnUOA==
    PORT: AgA/dgc6ES9RoAakZymhHt+vtPtTSGxUPYDVW2zKNYa2+zMK9cFv1PevvGbITgkgdfD90SXdTiLdspRLgOqbCp12OUvb1XqEhJNnBOlaRrDREW+n0N/p314bASMudnKnFdLhY7G3JAAXwIPIZSxNoNrdKPlNqrjJrHjvlBdkCZd7KV9XPUD+3Z33jkuRfc269VnG7dIz5wKnx60mh8ckm+zDkiBxHnpf2ccJQ1S3Q9P+141vV5s00t6Xq2slQ5P+ZFSBHI+iCUdadF/SqE2h3ufc/GTs3oPZewQ5+yKi4YCP7Xbtk6KgqqnwqaGFlm+yKIl8WdnoNAlAB4eDZA58LSzVmLSa6lWY/MatJtbCLrlzTOpBwK9bI3MtBgVeipwQg9wKtn/X7+8JlYpMYIx5vWiM8TuPrv7CUhsm6hl41c9IAiq7cfqrnlj38zeDajSBY1upnDZtTxTIEo4F+LJikddOMaH4NWlNfqCSgdIIHG/LHQGJnoNjo6glgSODCfP87YNF6rh6T9RogvFzhI5zMnOp5AdLWpmwCoPSQIhXTXh5VFBYUImBnLsSWgSVz6ynjQFLoSLZjiR6mjgJgFpHtaGRX9ZQZrXAm4Dcif9OfXd7tv8zy9FsGOKbONQOr6R5FXrKPTusBYO89dmROfxBAxkvLW3ZfcNwz+nqwOv98oiwzHA4vMG9AlhWJqXyCsSa4Xxl6ZSr
  template:
    metadata:
      creationTimestamp: null
      name: admin-service-secret
      namespace: pharmaceutical

