
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/akalanka47000/pharmaceutical-user-service:f69483729152ef6db5cfe4b8c6a78d2d1aa82891-1
          envFrom:
            - secretRef:
                name: user-service-secret
          ports:
            - containerPort: 8080
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
          resources:
            requests:
              cpu: 11m