
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/akalanka47000/pharmaceutical-user-service:eff5f0db8489a4ea7c473b6aedd38a0800f67ce2-1
          envFrom:
            - secretRef:
                name: user-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
              - echo
              - 123
          readinessProbe:
            exec:
              command:
              - echo
              - 123
          resources:
            requests:
              cpu: 10m
