apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgAgouL93ToJ4pToCV/yG/tic1qgx0rtQKLP/T71sNIgZbQie/Zymw2LZp1FZFnyDt10G1CID7cxJSaYPAGQLGWPEq4EOEXpHatgbMjyJB4EvWiz5FQBejRGKff0qv37SzVagmFwl+TDA6aQM77vQEHkZpSCnSHQdvrX26GALayNMF5AiuMs1+o6/AnV5/HgYQwB8UFtSNBQ+MH8YmqXT9b1Ni8pH8CfSd8kq8pMfsECcDsGE8G3fVggxqKWl+RGL19fZw7wiH0YtSdmX9bsUTnl4xFEYmWoJYC06ybR1jFzjHVi9SUQSkNppsLA9yrhE7X9KNPZxmC2Q8dSBv0D4kO2sndExLmSEgXzOtQosmXkhH19Q6y6fo/PPPBb+xuDzSXWHW4mARHQFWETWvLTPTvn9pyv5myLv7v31Yx/AaNW2vQIl50ZldSsXG2Z/lBW1b147srKhbbtP9YfXBlbTlrF2/8KYKUbYFKkU7bzdx5DrBDJmYsNyTRWWSEwbwcSioP3Hw2p9g3rEUVysVdm8Q4FP/f859P5CtCDgwAOPWKpu5zVwzI4SGJoXvcUmHVYEBCiZLI61uoG7OcgsG/ZrdeZf+XCQe0k9S6SVJS5yc3m/G+XmFo3vX+hp+rGoLBnrYZxXDFkJu9x1UHt++QPEq1E4ZaGFU56dX+dqE1qQ2cfx8THyZ9SNMTdvFA34RuEl3d9jZGI365IFk4w6ujevfDdh2aI6lEzwjLLScyuUoAxWuUH5V+TlEKDGYBljvKwFneOdTivP5zSluegVIKs0j5sDSkuc7qpfTFzJH/eCsU3a1qYrsafk1AqQ1aqjQ==
    PORT: AgAjC33tsrFFqrVJP1ZiImyKxlLIBt/lQFcHwfpg83aTrY1FqeS3Mch8ZCbK0SPcVil/CKDdXHyhdCXNFfF12Whk0ydidIyUVb4Q/pagJIq9zTmjmbOA6L+pxWmtzAi9dZOnhChabBeiibpkq3B9Lxk1c+0+Jps8eOq3YPuY6SLeb+AtLpk9AnkgozfIDPUY/lqWz3W5UdXBbiPXcKyCFDjb28PSUlBWSI+DgEmuOhQ+HLPOXYAKbTJsXG2P/ND/ykTJji5FYYBfAITv43bm2bZecfX8z1fbWcIod1Vlmay9+VGt4Jhny9/yohqEzLuhIW+Gku7fzXPj7TloJV4/XSTAYKgt949vibIZAXICFTBC+apsxdbpAq1n1ZU/qAKB6xTLUKsDhhmITeoXYMMG2knNK6fFmVqWTadC8VyHnbSi7nJ+L4y7j8oi7yaH3jfzjAhrl44XgpLkfdt5XqMcSXqjk8ZnNRG7QFwKG0omW4uqTHpsnXclwOvtxlDRxtcG7tkUPuXymUrjpPsjcWbNxMgOzNDJue1pCXWDqc5312F0kSE6trZRiWx/gpl2KsmZ4eDpG85KYVkXztkbz/PNj5UzJe+YLZvWOnDH81Pjvaf0t2mq9FQJUuk64lngbKw8VQo/Pmviv6irKvzdn8RzuZbxTOdQf5AQppDGmsnexGKeoRHY9noIwius4ShRrvg6XJodz+Eb
  template:
    metadata:
      creationTimestamp: null
      name: user-service-secret
      namespace: pharmaceutical

