apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    STRIPE_PUBLIC_KEY: AgBc3VypROcxQnKYxZK/sc4+afAKh1Ta2aDzuBdnGVpb3KCD2UYEjV3co5lkt6HUG6xKz7KO0kR+0O8XdtiK6cVzS2Ra1RBJN+Lutt3WLmnGsLISMInJ2uZmZCSAlelRi3ECozwcHObVAV3AwJfks7N33c6aBQpPR2ElBjdfkuf2T0y0znzKncOCzwsulSdvB+uogDOD7tT4veJ12GchV7bToUsqQ2VNtL0eCriFE+QJcX4tdbBg7cmacWXF9xL78dwzjzJ0J0RrYVQRpSxHveErM84ZedqYPXRnCz3IdkwM/vXk0uZnoBCigFEbP3LXeKLe+fQPcQmV+L6VEzwYoPycFIk4Di7GtqKgxefGxbcSfxJR+LIHo4zSWqyqCSlLdKLPNfjREdSSwdbqV3Jq3nuMh8uxJKuyMwRa+Fpf7M2qXI41OUz3aNgWXfS3n7cz8f8hcP/9NR/8bAH5NDwUDW1SeuaxAmKE6xrfckq/1wxTkQArvvF6/KIAJmvRBv9rXGUT6YmUvRS+OsL9EcF4wBJr8i+0lI0chyTqAFd3y3RGUVD2QuTJIRNV8WIRF6OWrVYsb7ES3FeC7zqCItEx6UwaVK5bNKBg1HwVLsrxlYWT0HK2r61+5iC1nl68OTWHUgr2RpGmDBZ8kh+y0CT3vidfNnd+w2iLEg0t/x9j9PwSLyQREC49skz/oWSYvzPLjv0CHOC7Vvm4tmjQ
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secret
      namespace: pharmaceutical

