apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    STRIPE_PUBLIC_KEY: AgAiEAJTez6Ouv7HBU822T05T2SdERtiUxBCs4cLSD/EykcyY0VIfuPw5Uh9dOwBu2kuUX1zICvgjFzdHktQ1ex6PJMWPTGCgqh+MZ+axclj8QpZDibhojbJSHegB/xqCtX8ZBVJR2TYA+wocvzgNFZ8dZdFoJRG+FFvqPJ19a9LG+DFW11QV13oniWftHi0aDXA9r9WkJcy38AApt70oP6U5Pts8bH2EkN4dz++Zkv1lq3g6YtNAaLJ/e/AJ7xhPafJJB5s1mCNrCIFHh5djl/g3wmi6aE7WbEQzmM39ryGjay23vn9qBhNpFiEI2rUt1IWR1I9vNg0iMzKB49aUbz6407cI3p5pUxSKmRSet8HSJWusWZxie6oIr2kegTQPBa9t068UQhRXhnAKwHqKY3IPjGwbEw/65RIQ+X8dkN0fnlNF+vt36H6vipxR78UofSSF/Z4IJdBD64XL4g+OqzixHQ2u1+DaO+3Tml67HV/eWN/6NoLYfqqL8+QaNrw7LlwOBMembR42DWOHC6sZakEobjDvQ5rFAUEhVno+gu6GdscoAokGutJIZabJ343hrwKZTA0KI+tuiGRzg8DsMZ0weNMcwa0EwXidM5QCnk9g5ie50oBSamdTd65KR2c8YLv9qJXdbxyTO/rrOpplOEmHjTpW4I4pRYp+4Jd0Ra9JDBEHPGCHU9J6sPtE6QnA+4pfsYevt0ZxaKf
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secret
      namespace: pharmaceutical

