apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pharmaceutical
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 8080
          - path: /system
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 8080
