apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-service-secret
  namespace: pharmaceutical
spec:
  encryptedData:
    DB_URL: AgCwGxI/KouDDrIaDsWx0uqw1NzPgDrQqVYn2W/yAMOsMUBlYvL0L2jIQvecAVeg+GeHkeowOSJBALpjEOZGudno2tHl2l0B9r76VlDQ5UcBzoNv9xIO4IDkawBhhehYlCdCk2Y/dIstqgQxnGHr48gKOad2WZOogNdAM0yXs5LQSN88DAY0nqm02/cz5ic0SwAfqfg+GOSdTAtqqq2DOV7LrINExBZppVrrIeEwHVirYFRQJmGou7zeVwAPq44FyHP69eun7OkreLrQbxsRSXsD4B0MsWbCJYM5+dRmrOA70v19xn+jZsSnR/1nIkKzPBPM7D1ubn4WYKsgAClvP3vog5gIV0k/eRGZjPrNdvGE63QstDvSangGby1HchepfJ0JfPO2QjiRiTupfJZhxJkf3TywZYECJgFSVZ1fDglLtBBsk212HqeW7qSw/w1ukH+3Vj1Gi29OF5v9NM8jE0dqx1o0cpnBU1dB0DTIBMW0y3bsdVZ9ZI2mduhZ5xhrTgDAPT0kMdMXOzAYrcuNJFUnQbiGrDN6QEUL6v6p0fyypY++4LOdKO/CD5A+vM/NqCowto+ro6Wkm7Gl+lW0XY/LQDXM8rDoWo0yPeVstk3yCn5BB09Z+F7+xKxP0Xdo5YGRhfxUAw+UYXDSNeUnjsjNWmz/aYQyjSMaOrZXNtLOSbvuWvp5+8xCKtgT9jVPD3RmzAdNVIZm5NVQmCwrNS5OHqUuv5hHb9K2DHKqbGFEraCIENC53Uwa58JH+SVo+AB09g0Gm2Jp2UAvrJ2/S21k/9hbcsN8XodaBqTpwv+qI47zc+hAOOAu5FOQaQ==
    PORT: AgC7e4y/Bngv5MfcesSeKEvBmB445ueDqdM/vwjUqhu8ke/UDpgyQ5P20499OymqJ21pMpBMOl+UDoY36ZxdmXqSrAJixI5Xbm6x+CSQDL9MrbT5wQIf4ewxtJLlWXwSbtPl4JxQDs2NKxS2JydtXPsaLJsjC8hMUxUFyfiie3YjyJedHGZrGat3JbNPCPSYLIBek5Rjxpc6RCHRUyVZSRvdeJUqd0rxXdz1tLOPqv3vQkBxfhdkNz6Vgvc+SfkVixV4+hXDf2P6+lKAk884MvEgW67uXLYhCPTst9ZRK8m5FM1kGAAcrfarFfcFbi4FQerGPN1dPj7fkQGuhUsMxFRN9UrxdKzy+O/Izp3Peew0JDJVL18bKZsEQytjZMViMZs3xvoXcnnMoZwqb+GeC/wk8P/2sisvUqxvOYz/tVHTlUn0TWnb3dh2LCX8rOYsHvvrb4wyJ5stpyf8D+EzGaSkEtPNnVlR+k92rm5GpojsAHgTmP3qT3QdVfsoW2qAHRfoBamDoxIKEWvlrlYNdrVTG+Xcwm54UfOmBuBUNYqvFWN3BddOnm830592OoUsOEJAADvcBVb5Nuo4AKt5QZrSxE9NQWpKO6Zd2MfKLbW8AwzqnDpjxqniWZH/d1rJ4I78nD9pexiVIO372+5zOXxEggufE+O97OnUVLNpRYJPBoceUR33JPs4fxJ9lMHXDmn0G3t5
  template:
    metadata:
      creationTimestamp: null
      name: order-service-secret
      namespace: pharmaceutical

