
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer-service
  labels:
    app: buyer-service
spec:
  selector:
    matchLabels:
      app: buyer-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: buyer-service
      labels:
        app: buyer-service
    spec:
      containers:
        - name: buyer-service
          image: ghcr.io/akalanka47000/pharmaceutical-buyer-service:5a7149af2dda3d29b1f834f3cd0dfb841e2da327-1
          envFrom:
            - secretRef:
                name: buyer-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
